### ISSUE TITLE
Publishing the code search guide on the learn site?

### ISSUE THREAD

**Issue by sqs** [sourcegraph/learn#113]
Do you all think the learn site is a good place for the [Code search guide](https://docs.google.com/document/d/1fw0ee634RwLGJgB4jHi049k5K2VL-q47JgOcZEc01IU/edit) to live? That linked gdoc has an overview of what it will contain. IMO the learn site would work well for it (and thank you for making it! :tada:).

@jennybergen Were you thinking it'd live here, or did you have somewhere else in mind?

Our model is an article like https://stripe.com/atlas/guides/saas-pricing, which is also on a "learn site" (i.e., not a technical doc site).

Other options:

- We could publish the code search guide in our doc site like https://docs.sourcegraph.com/adopt/code_search_in_monorepos (which is another general article that's not completely Sourcegraph-specific). Cons: this would make it seem less neutral and more Sourcegraph-specific, and we want the code search guide to describe all code search tools.
- We could publish the code search guide on its own site, but that would require a lot more effort/maintenance.
- We could publish the code search guide on about.sourcegraph.com, but that also seems less neutral and more Sourcegraph-promotional.

**Comment by ltagliaferri** [comment]
We are definitely open to this, would love to hear more from the Content team!

**Comment by jennybergen** [comment]
@sqs after speaking with @ltagliaferri and Erica, we agree that the Learn site would be a good place for the Code Search Guide. 

I do want to surface one _temporary_ concern. Since the current state of the Learn site features only Sourcegraph-specific content, I worry that it may suffer from the same issue you pointed out above under posting on the docs site: 

> Cons: this would make it seem less neutral and more Sourcegraph-specific, and we want the code search guide to describe all code search tools.

I know the plan with the Learn site is to create product-agnostic content, so I don't think it's a problem in the long term but still want to mention it to make sure this is not an issue when it comes to asking others outside of Sourcegraph to contribute. 

The other awesome thing about posting on the Learn site is that we have engineering support to make the guide look nice right now! I spoke with Katy about building this on the Learn site today (with Lisa's blessing!) and showed her the Stripe example for inspiration. Their layout is similar to what's already on the Learn site, so Katy said getting a V1 of the guide built and published by Thursday of next week (July 29), should be doable. 

And lastly, Erica and I discussed having the URL be https://learn.sourcegraph.com/guides/code-search. We want to include "/guides" in the URL to have a home for future guides on the Learn site. Okay by you both?

**Comment by ltagliaferri** [comment]
Thank you for the update @jennybergen — this all sounds really great to me! Really glad to provide a home to this important work.

I will see if we can also privilege some quick changes to the look of the site to make it seem less Sourcegraph-centric

**Comment by ltagliaferri** [comment]
Closing this as this will be living elsewhere, see https://github.com/sourcegraph/codesearchguide.org
